- name: Installing metricbeat
  ansible.builtin.apt:
      name: metricbeat={{ version }}

- name: Configuring metricbeat
  ansible.builtin.template:
    src: metricbeat.yml.j2
    dest: /etc/metricbeat/metricbeat.yml
    owner: root
    group: root

- name: Starting metricbeat service
  ansible.builtin.service:
    name: metricbeat
    state: started
    enabled: true